// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Z5z66j1ZCRHbOf2dJxrYUft3ssRRxqM',
    appId: '1:696756591778:web:b154ec8338f2dd4d5f4bfb',
    messagingSenderId: '696756591778',
    projectId: 'news-app-5376b',
    authDomain: 'news-app-5376b.firebaseapp.com',
    storageBucket: 'news-app-5376b.appspot.com',
    measurementId: 'G-ETQ1WW6G52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjw8w99OlsJTXlb2FgL0KH6F-OlheCRpQ',
    appId: '1:696756591778:android:19d3f5d3239cea805f4bfb',
    messagingSenderId: '696756591778',
    projectId: 'news-app-5376b',
    storageBucket: 'news-app-5376b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsk5CalWWWSS-l71ho_9ncYgU10QIi6-0',
    appId: '1:696756591778:ios:6a41cfe93eeb6cd95f4bfb',
    messagingSenderId: '696756591778',
    projectId: 'news-app-5376b',
    storageBucket: 'news-app-5376b.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsk5CalWWWSS-l71ho_9ncYgU10QIi6-0',
    appId: '1:696756591778:ios:6a41cfe93eeb6cd95f4bfb',
    messagingSenderId: '696756591778',
    projectId: 'news-app-5376b',
    storageBucket: 'news-app-5376b.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2Z5z66j1ZCRHbOf2dJxrYUft3ssRRxqM',
    appId: '1:696756591778:web:f9465968d3465ee95f4bfb',
    messagingSenderId: '696756591778',
    projectId: 'news-app-5376b',
    authDomain: 'news-app-5376b.firebaseapp.com',
    storageBucket: 'news-app-5376b.appspot.com',
    measurementId: 'G-7Q9NCFRCP2',
  );
}
